version: '3'

services:
  web:
    environment:
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
   
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000

    volumes:
      - .:/app
    
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    volumes:
      - ${CERT_PATH:-~}/cert.pem:/etc/ssl/certs/SSLWebCert.pem:ro
      - ${CERT_PATH:-~}/cert.key:/etc/ssl/private/SSLWebCert.key:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - web
