version: '3'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
 
  apache:
    build:
      context: .
      dockerfile: Dockerfile.apache
    ports:
      - "80:80"
    depends_on:
      - web
