name: Check Source Branch

on:
  pull_request:
    branches:
      - "dev"
jobs:
  check-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check if source branch is pre-prod
        run: |
          if [[ "${{ github.head_ref }}" != "pre-prod" ]]; then
            echo "Error: Pull requests to master must come from pre-prod branch!"
            exit 1
          fi
